server/config/routes.rb
Server::Application.routes.draw do
  resources :recipes do
    collection do
      get :reload
    end
  end
  resources :hosts do
    resources :recipes, :attributes
    
    member do
      get :current_state
      get :new_state
      get :diff
      post :set_recipes
      get :reset
    end
  end
  
  resources :versions do
    collection do
      delete :remove
    end
  end
  
  root :to => "hosts#index"

end

server/app/models/host.rb
class Host
  include Ripple::Document
  many :recipes
  
  key_on :name
  
  property :name, String
  property :ssh_user, String, :default => 'root'
  property :ip, String
  property :state, String, :default => 'undefined'
  
  property :current_states, Array, :default => []
  
  property :last_run, Array, :default => []
  property :lorenz_attributes, Hash, :default => {}
  
  # state_machine :state do    
  #   event :converging_started do
  #     transition :enqeued => :in_progress
  #   end
  #   
  #   event :converge do
  #     transition any => :enqeued
  #   end
  #   
  #   event :success do
  #     transition :enqeued => :success
  #   end
  #   
  #   event :failure do
  #     transition :enqeued => :failed
  #   end
  # 
  # end
  
  # Хак для стейт машины
  # def initialize(attrs={})
  #   @attributes = attributes_from_property_defaults
  #   self.attributes = attrs
  # end
  
  # def current_state
  #   serialized_current_state ? Lorenz::NodeList.deserialize(serialized_current_state, lorenz) : Lorenz::NodeList.new
  # end
  
  # Хак. links в riak ordered, а вот walk (им получаются ассоциации) нет. Использует патч в riak-client
  # TODO Чувак сказал что это нифига не православно и их ordered это сайд эффект. http://github.com/seancribbs/ripple/pull/79
  # Придумать что-нить нормальное
  def ordered_recipes
    index = recipes.index_by { |v| v.key }
    recipes.send(:links).map { |v| index[v.key] }
  end
  
  def converge_completed(state, history)
    update_attributes :state => state, 
                      :last_run => history, 
                      :current_states => lorenz.current_state.serialize, 
                      :lorenz_attributes => lorenz.attributes
  end
  
  def update_state(to)
    update_attribute :state, to
  end
  
  def reset!
    self.current_states = Lorenz::NodeList.new.serialize
    save
  end
  
  def lorenz_recipes
    ordered_recipes.map(&:lorenz)
  end
  
  def lorenz
    @lorenz ||= Lorenz::Host.new :ip => ip, 
                                 :ssh_user => ssh_user, 
                                 :recipes => lorenz_recipes, 
                                 :current_states => current_states,
                                 :name => name,
                                 :attributes => lorenz_attributes
  end
  
  def to_json
    {
      :current_state => current_states,
      :attributes => lorenz_attributes
    }.to_json
  end
  
end

server/app/controllers/hosts_controller.rb
class HostsController < InheritedResources::Base
  respond_to :html, :json
  
  def show
    show! do |format|
      format.json do
        render :json => resource.to_json
      end
    end
  end

  
  def destroy
    resource.destroy
    flash[:success] = "Host #{@host.name} deleted"
    redirect_to root_path
  end
  
  def set_recipes
    resource.recipes = params[:ids] ? params[:ids].sort_by { |k, v| k }.map { |k, id| Recipe.find(id) } : [] # По идее тут не ordered хеш 
    resource.save
    render :text => ''
  end
  
  def current_state
    @state = resource.current_states
  end
  
  def new_state
    resource.lorenz.apply_recipes
    @state = resource.lorenz.node_list
  end
  
  def diff
    resource.lorenz.apply_recipes
    @diff = resource.lorenz.diff
  end
  
  def attributes
    
  end
  
  def reset
    resource.reset!
    redirect_to host_path resource
  end
  
  def collection
    @hosts ||= end_of_association_chain.all
  end
end

server/app/helpers/hosts_helper.rb
module HostsHelper
  def ordered_hosts(hosts)
    order_map = { 
      :in_progress => 1,
      :success => 2,
      :failed => 3,
      :undefined => 4
      }
    hosts.sort_by { |v| order_map[v.state.to_sym] }
  end  
end

server/app/views/hosts/_form.html.haml
- semantic_form_for @host do |form|
  = form.inputs :name, :ip
  = form.buttons

server/app/views/hosts/_state_browser.html.haml
- if @state
  %ol
    - @state.nodes.each do |node|
      %li
        %pre= node.inspect
        
- else  
  %p State is undefined

  

server/app/views/hosts/current_state.html.haml
- if @state
  %ol
    - @state.each do |node|
      %li
        %pre= node.inspect
        
- else  
  %p State is undefined

server/app/views/hosts/diff.html.haml
%ol
  - @diff.each do |action|
    %li
      %pre= action.to_s

server/app/views/hosts/edit.html.haml
%h2= @host.name

= render :partial => 'form'

server/app/views/hosts/index.html.haml
%h2 Hosts list

%p= link_to "Add host", new_host_path

.hosts_list
  - ordered_hosts(@hosts).each do |host|
    %a{ :href => host_path(host) }
      .host{ :class => "host_#{host.state}" }= host.name

server/app/views/hosts/new.html.haml
%h2 Add host

= render :partial => 'form'

server/app/views/hosts/new_state.html.haml
= render :partial => 'state_browser'

server/app/views/hosts/show.html.haml
:javascript
  WEB_SOCKET_SWF_LOCATION = "/WebSocketMain.swf";
  // Set this to dump debug message from Flash to console.log:
  WEB_SOCKET_DEBUG = true;
  var recipesSortables;
  window.addEvent('domready', function() {
    function debug(str){ console.log(str); };

    ws = new WebSocket("ws://localhost:4001/");
    ws.onmessage = function(evt) { 
      var msg = JSON.decode( evt.data )
      var li = new Element('li', { 'class': 'action_' + msg[0], 'html': msg[1] })
      li.inject($("current_run")); 
    };
    ws.onclose = function() { debug("socket closed"); };
    ws.onopen = function() {
      debug("connected...");
      ws.send("current_run #{@host.name}");
    };
    
    recipesSortables = new Sortables('#avaliable_recipes ul, #host_recipes ul', {
      clone: true,
      revert: { duration: 500, transition: 'elastic:out' },
      onComplete: function() {
        new Request( {
          url: '/hosts/#{@host.key}/set_recipes',
          data: {
            ids: recipesSortables.serialize(1)
          }
        }).send();
      }
    })
    
  });


%h2= @host.name

%p
  = link_to 'Current state', current_state_host_path(@host)
  |
  = link_to 'New state', new_state_host_path(@host)
  |
  = link_to 'Diff', diff_host_path(@host)
  |
  = link_to 'Attributes', host_attributes_path(@host)
  |  
  = link_to 'Edit', edit_host_path(@host)
  |
  = link_to 'Delete', host_path(@host), :method => :delete


.grid_5.recipes_list#avaliable_recipes
  .recipes_type Avaliable recipes
  %ul
    - Recipe.all.select { |v| !@host.recipes.include?(v) }.each do |recipe|
      %li{ :id => recipe.key }
        #{recipe.name} (#{recipe.key})
    

.grid_7.recipes_list#host_recipes
  .recipes_type Host recipes
  %ul
    - @host.ordered_recipes.each do |recipe|
      %li{ :id => recipe.key }
        #{recipe.name} (#{recipe.key})
      
.clear    

/ %p 
/   - form_tag host_recipes_path(@host) do |f|
/     = select_tag "recipe_id", options_from_collection_for_select(Recipe.all.select { |v| !@host.recipes.include?(v) }, "key", "title")
/     = submit_tag "Add recipe"
/ 
/ %ul
/   - @host.recipes.each do |recipe|
/     %li
/       = link_to recipe.name, recipe_path(recipe)
/       [#{link_to('Remove', host_recipe_path(@host, recipe), :method => :delete)}]
      
%h3 Current run

#debug

%ul#current_run
      
%h3 Last run

%ul
  - @host.last_run.each do |res, cmd, error|
    %li{ :class => "action_#{res}"}
      = cmd
      - if error
        (#{error})